echo "username: `whoami`"
echo "groups: `groups ndarapaneni| cut -d " " -f1`" 
echo "My Hostname is `hostname` and my domain name is `domainname`"
echo "Current Date: `date "+%Y/%m/%d"`"
echo "Current Time: `date "+%H:%M:%S"`"
echo "Day of Today: `date "+%A"`"
echo "My Time Zone: `date "+%Z"`"
echo "Cureent logged in users in server: `who`"
echo "Total directories in my home dir: `find . -maxdepth 1 -type d|wc -l` "
echo "Total files in my home dir: `find . -maxdepth 1 -type f|wc -l` "
